-- PROMPT DB-14. PRD §37 Testing Strategy: "seed factory (LexFlow.Seeder)
-- producing deterministic demo tenant (200 clients, 1k matters, 5k
-- hearings, 10k entries) used by all test tiers and demos." This script
-- only creates the tenant + one branch — the bare root every other
-- 16_Seed script above already assumes via the fixed demo tenant id
-- '00000000-0000-0000-0000-000000000001'. The full 200-client/1k-matter/
-- 5k-hearing/10k-entry volume is generated by LexFlow.Seeder (API-side, a
-- later prompt), not raw SQL — this is deliberately sized small: exactly
-- one tenant and one branch, matching the seed factory's demo tenant id so
-- that seeder can attach its generated data to the same tenant/branch
-- rather than creating a second one.
INSERT INTO core.tenants (id, name, slug, status, plan_tier, region, default_locale, default_currency, fiscal_year_start_month, timezone)
VALUES (
  '00000000-0000-0000-0000-000000000001',
  'LexFlow Demo Firm',
  'lexflow-demo',
  'Active',
  'Enterprise',
  'india-central',
  'en-IN',
  'INR',
  4,
  'Asia/Kolkata'
);

INSERT INTO core.branches (id, tenant_id, name, code, address, tz, gstin, series_prefix)
VALUES (
  '00000000-0000-0000-0000-000000000002',
  '00000000-0000-0000-0000-000000000001',
  'Head Office',
  'HQ',
  jsonb_build_object('city', 'New Delhi', 'state', 'Delhi', 'country', 'India'),
  'Asia/Kolkata',
  NULL,
  'HQ'
);
